name: CI Pipeline GitHub Actions For Parent Module

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build Parent Module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '1.8'
          distribution: 'adopt'
          cache: maven

      - name: Run maven build command from parent folder
        run: mvn clean package

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
          distribution: 'adopt'
          cache: maven

      - name: Run Test Cases
        run: mvn clean '-Dtest=*Test' -Djacoco.destFile=target/jacoco.exec test

      - name: Upload jacoco exec test results
        uses: actions/upload-artifact@v2
        with:
          name: tests-jacoco
          path: target/jacoco.exec

      - name: Tests Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests Report
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true